---
title: "Case Study 2"
author: "Carl Keusseyan"
date: "7/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load the libraries
library(ggplot2)
library(magrittr)
library(dplyr)
library(tidyr)
library(forcats)
library(matrixStats)
library(GGally)
library(caret)
library(corrplot)
library(esquisse)
library(cowplot)
library(ggExtra)
library(ggthemes)
library(maps)
library(usmap)
library(naniar)
library(olsrr)
library(stringr)
library(e1071)
library(FNN)
library(MASS)
library(caret)
library(e1071)
library(reshape2)
library(RANN)

```

```{r}
# pulling in datasets ----
df <- read.csv("CaseStudy2-data.csv")

# check the structure of the dataset
str(df)

# check for missing data
gg_miss_var(df)  # looking at the plot we can see that there is no missing data 

```


```{r}
#>>>>> Analysis ----

# try 1 - let us plot pairs to see if there is any patterns immerging between variables
# Observationis: Some pairs show some corealtion  - expanding the nuimber of pairs
dfa1 <- df %>% dplyr::select(JobSatisfaction, OverTime, StockOptionLevel, TotalWorkingYears, YearsSinceLastPromotion, Attrition)
pairs(dfa1)

# try 1 - let us plot more pairs to see if theire is any patterns immerging between variables
# Observationis: Some pairs show some corealtion 
dfa2<- df %>% dplyr::select(JobSatisfaction, OverTime, StockOptionLevel, TotalWorkingYears, YearsSinceLastPromotion, EnvironmentSatisfaction, JobInvolvement, NumCompaniesWorked, TrainingTimesLastYear, Attrition)
pairs(dfa2)

# Let us dive into the data and investigate the ones that are shwoing some corelation

# Let us see which Job role makes the most Monthly Income
# Observation: Managers & Research Directors, on the average, make the most Monthly Income
ggplot(df) +
 aes(x = JobRole, y = MonthlyIncome) +
 geom_violin(adjust = 1L, scale = "area", fill = "#0c4c8a") +
 labs(title = "Monthly Income by Job Role", subtitle = "Violin Plot", caption = "Managers & Research Directors, on the average, make the most Monthly Income") +
 coord_flip() +
 theme_minimal()

# Let us see which Job role stays in the company the longest
# Observation: Managers & Research Directors, on the average, stay in the company the longest
ggplot(df) +
 aes(x = JobRole, y = YearsAtCompany) +
 geom_boxplot(fill = "#c6dbef") +
 labs(title = "Years At Company by Job Role", subtitle = "Boxplot", caption = "Managers and Research Directors, on the average, stay in the company longer") +
 coord_flip() +
 theme_minimal()

# Let us see if there is a gender difference in Monthly INcome and Job Role
# Observation: Female Research Directors, on the average, make more Monthly Income than their Male counterparts
ggplot(df) +
 aes(x = JobRole, y = MonthlyIncome, fill = Gender) +
 geom_boxplot() +
 scale_fill_hue() +
 labs(title = "Monthly Income by Job Role by Gender", subtitle = "Boxplot", caption = "Female Research Directors, on the average, make more Monthly Income than their Male counterparts") +
 coord_flip() +
 theme_minimal()

# Let us see Job Satisfaction by Job Role / Overtime
# Observation: ust because you get Overtime does not necessarily mean you have Job Satisfaction
ggplot(df) +
 aes(x = JobRole, y = JobSatisfaction, fill = OverTime) +
 geom_boxplot() +
 scale_fill_hue() +
 labs(title = "Job Satisfaction by Job Role / Overtime", subtitle = "Boxplot", caption = "Just because you get Overtime does not necessarily mean you have Job Satisfaction") +
 coord_flip() +
 theme_minimal()

# Let us see Job Satisfaction by Job Role / Attrition
#observations: Job Satisfaction plays a role in Attrition
ggplot(df) +
 aes(x = JobRole, y = JobSatisfaction, fill = Attrition) +
 geom_boxplot() +
 scale_fill_hue() +
 labs(title = "Job Satisfaction by Job Role / Attrition", subtitle = "Boxplot", caption = "Job Satisfaction plays a role in Attrition") +
 coord_flip() +
 theme_minimal()

# let us see Work Life Balance by Monthly Income / Attrition
# Observations: Work Life Balance appears to have a role in Attrition (more work Life Balance less Attrition)
ggplot(df) +
 aes(x = MonthlyIncome, y = WorkLifeBalance, fill = Attrition) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 geom_smooth(span = 1L) +
 scale_fill_hue() +
 labs(title = "Work Life Balance by Monthly Income / Attrition", subtitle = "Scatter Plot with Trend Line", caption = "Work Life Balance appears to have a role in Attrition (more work Life Balance less Attrition)") +
 theme_minimal()

# let us see Monthly Income / Environment Satisfaction
# Observations:# Intersting to note the Environment Satisfaction effect on Attrition (more Environment Satisfaction less Attrition)
ggplot(df) +
 aes(x = MonthlyIncome, y = EnvironmentSatisfaction, fill = Attrition) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 geom_smooth(span = 0.75) +
 scale_fill_brewer(palette = "Set1") +
 labs(x = "Monthly Income", y = "Environment Satisfaction", title = "Monthly Income / Environment Satisfaction", subtitle = "Colored by Attrition", caption = "Intersting to note the Environment Satisfaction effect on Attrition", fill = "Attrition") +
theme_minimal()

# let us see Distance From Home by Environmental Satisfaction / Attrition
# Observations: Distance From Home appears to have a role in Attrition (more Distance From Home more Attrition)
ggplot(df) +
 aes(x = EnvironmentSatisfaction, y = DistanceFromHome, fill = Attrition) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 geom_smooth(span = 1L) +
 scale_fill_hue() +
 labs(title = "Distance From Home by Environmental Satisfaction / Attrition", subtitle = "Scatter Plot with Trend Line", caption = "Distance From Home appears to have a role in Attrition (more Distance From Home more Attrition)") +
 coord_flip() +
 theme_minimal()

# let us see Attrition by Job Role
# Observations: Job Roles of Sales Representative and Human Resources experience the most Attrition
ggplot(df) +
 aes(x = JobRole, fill = Attrition) +
 geom_bar(position = "fill") +
 scale_fill_hue() +
 labs(title = "Attrition by Job Role", subtitle = "BarPlot set to Fill (1.00 is considered 100%)", caption = "Job Roles of Sales Representative and Human Resources expereince the most Attrition") +
 coord_flip() +
 theme_minimal()

# let us see what Job Role tends to have the oldest 
# Observations: Managers and Research Directors tend to be older
ggplot(df) +
 aes(x = JobRole, y = Age) +
 geom_boxplot(fill = "#fde725") +
 labs(x = "Job Role", title = "Age by Job Role", subtitle = "Boxplot", caption = "Managers and Research Directors tend to be older") +
 coord_flip() +
 theme_minimal()

# let us see Monthly Income / Distance From Home
# Observations:# Intersting to note the Distance From Home effect on Attrition
ggplot(df) +
 aes(x = MonthlyIncome, y = DistanceFromHome, fill = Attrition) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 geom_smooth(span = 0.75) +
 scale_fill_brewer(palette = "Set1") +
 labs(x = "Monthly Income", y = "Distance From Home", title = "Monthly Income / Distance From Home", subtitle = "Colored by Attrition", caption = "Intersting to note the Distance From Home effect on Attrition", fill = "Attrition") +
theme_minimal()

# let us see Monthly Income / Stock Option Level
# Observations:# Intersting to note the Stock Option Level effect on Attrition
ggplot(df) +
 aes(x = MonthlyIncome, y = StockOptionLevel, fill = Attrition) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 geom_smooth(span = 0.75) +
 scale_fill_brewer(palette = "Set1") +
 labs(x = "Monthly Income", y = "Stock Option Level", title = "Monthly Income / Stock Option Level", subtitle = "Colored by Attrition", caption = "Intersting to note the Stock Option Level effect on Attrition", fill = "Attrition") +
theme_minimal()
#
```


```{r}
#***** KNN ***** ----

# try 1 EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany ----
df1 <- df %>% dplyr::select(EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, Attrition)

#Internal CV
classifications = knn.cv(df1[,1:3],df1$Attrition, k = 3)
confusionMatrix(classifications,df1$Attrition)
# K=3           Accuracy : 0.8
#            Sensitivity : 0.9288          
#            Specificity : 0.1286 

classifications = knn.cv(df1[,1:3],df1$Attrition, k = 20)
confusionMatrix(classifications,df1$Attrition)
# k=20          Accuracy : 0.8391 
#            Sensitivity : 0.99178         
#            Specificity : 0.04286


# try 2 EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, WorkLifeBalance ----
df2 <- df %>% dplyr::select(EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, WorkLifeBalance, Attrition)

#Internal CV
classifications = knn.cv(df2[,1:4],df2$Attrition, k = 3)
confusionMatrix(classifications,df1$Attrition)
# K=3           Accuracy : 0.8011
#            Sensitivity : 0.9301          
#            Specificity : 0.1286 

classifications = knn.cv(df2[,1:4],df2$Attrition, k = 20)
confusionMatrix(classifications,df2$Attrition)
# k=20          Accuracy : 0.8391
#            Sensitivity : 0.99178         
#            Specificity : 0.04286


# try 3 EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, StockOptionLevel, DistanceFromHome, WorkLifeBalance ----
df3 <- df %>% dplyr::select(EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, StockOptionLevel, DistanceFromHome, WorkLifeBalance, Attrition)

#Internal CV
classifications = knn.cv(df3[,1:6],df3$Attrition, k = 3)
confusionMatrix(classifications,df3$Attrition)
#  K=3         Accuracy : 0.8207                **********************
#           Sensitivity : 0.9479                ***** Conclusion: this gives the best results in highest Specifity 
#           Specificity : 0.1571                ****************  while very high accuracy and Sensitivity

classifications = knn.cv(df3[,1:6],df3$Attrition, k = 4)
confusionMatrix(classifications,df3$Attrition)
#  K=4          ccuracy : 0.831
#           Sensitivity : 0.98219         
#           Specificity : 0.04286   

classifications = knn.cv(df3[,1:6],df3$Attrition, k = 20)
confusionMatrix(classifications,df3$Attrition)           
# k =20         Accuracy : 0.8379 
#            Sensitivity : 0.99041         
#            Specificity : 0.04286


# try 4 EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, StockOptionLevel, DistanceFromHome, WorkLifeBalance, MaritalStatus, Gender ----
df4 <- df %>% dplyr::select(EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, StockOptionLevel, DistanceFromHome, WorkLifeBalance, MaritalStatus, Gender, Attrition)
df4$MaritalStatus = as.integer(factor(df4$MaritalStatus))
df4$Gender = as.integer(factor(df4$Gender))

#Internal CV
classifications = knn.cv(df4[,1:8],df4$Attrition, k = 3)
confusionMatrix(classifications,df4$Attrition)
#  K=3         Accuracy : 0.8207
#           Sensitivity : 0.9479          
#           Specificity : 0.1571  



# *** Observations:  
#       Best Combination of variables: EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, StockOptionLevel, DistanceFromHome, WorkLifeBalance
#       Best K: 3
#       Accuracy : 0.8207                    
#       Sensitivity : 0.9479                 
#       Specificity : 0.1571                 
```

```{r}
# KNN Predict ----
dfp <- read.csv("CaseStudy2CompSet No Attrition.csv")
dfp1 <- dfp %>% dplyr::select(EnvironmentSatisfaction, MonthlyIncome, YearsAtCompany, StockOptionLevel, DistanceFromHome, WorkLifeBalance)

# Predict
knnpredictions <- knn(df3[,-7],dfp1, df3$Attrition, k=3)
knnpredictionsdf = data.frame(knnpredictions)
knnresults = cbind(ID = dfp$ID, Attrition = knnpredictionsdf)

# write it out
write.csv(knnresults[,1:2], file="Case2PredictionsKeusseyan Attrition.csv")

```


```{r warning=FALSE}
# Predict Monthly Income
# Plotting to look for patterns in the data ----

# Intersting to note the Total Working Years effect on Monthly Income
ggplot(df) +
 aes(x = TotalWorkingYears, y = MonthlyIncome) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 geom_smooth(span = 0.75) +
 scale_fill_brewer(palette = "Set1") +
 labs(x = "Total Working Years", y = "Monthly Income", title = "Total Working Years / Monthly Income", caption = "Interesting to note the Total Working Years effect on Monthly Income (The greater Total Working Year the greater Monthly Income)") +
theme_minimal()

# Intersting to note the Job Level effect on Monthly Income
ggplot(df) +
 aes(x = JobLevel, y = MonthlyIncome) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 geom_smooth(span = 0.75) +
 scale_fill_brewer(palette = "Set1") +
 labs(x = "Job Level", y = "Monthly Income", title = "Job Level / Monthly Income", caption = "Interesting to note the Job Level effect on Monthly Income (The greater the Job Level the greater Monthly Income)") +
theme_minimal()

```


```{r}
# ***** Linear Model ***** ----
# Choose the dataset 
dflm = df %>% dplyr::select(MonthlyIncome, TotalWorkingYears, JobLevel, JobRole)  

# Set Seed and Train/test sets 
set.seed(4)
splitperc = 0.70
index<- sample(1:dim(dflm)[1],round(splitperc*dim(dflm)[1]),replace=F)
train<- dflm[index,]
test<- dflm[-index,]

# linear model
linearmodel <- lm(MonthlyIncome ~ TotalWorkingYears + JobLevel + JobRole, data = train)
summary(linearmodel) 
# Oservation: GOOD!  We have an awesome Adjusted R-squared:  0.9443
#                    we have an awesome p-value of < 2.2e-16                

ols_plot_resid_fit(linearmodel)
ols_plot_resid_lev(linearmodel)
# Oservation: GOOD! we do not have wild outliers or high leverage points

ols_plot_resid_qq(linearmodel)
# Oservation: GOOD! Normality of Distribution - the points lie along a straight line.

ols_plot_resid_hist(linearmodel)
# Oservation: GOOD! Equal Standard Deviations - Bell Shaped Curve

ols_plot_cooksd_bar(linearmodel)
# Oservation: GOOD! We do not have any large  Cook's D points that could influence the fitted values
# data point having a large cook's D indicates that the data point strongly influences the fitted values.

# Predict
predictions <- linearmodel %>% predict(test)

# Get RMSE
dfRMSE = RMSE(predictions,test$MonthlyIncome)   
dfRMSE

# ***********
# Oservation: EXCELLENT RMSE of just 1055.184
#************

# LM Predict
dfpp <- read.csv("CaseStudy2CompSet No Salary.csv")
predictions <- predict.lm(linearmodel, dfpp)
predictionsdf = data.frame(predictions)
dfresults = cbind(ID = dfpp$ID, MonthlyIncome = predictionsdf)

# write it out
write.csv(dfresults[,1:2], file="Case2PredictionsKeusseyan Salary.csv")

```




